# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e64c1563cdcfc048082f82fe9db238097990093bc42656e0048f8c59b889bb9dd58efd17f271f3052f2109382279a5574ea543f07a14142eda0cc5b862a5df20

test:
  secret_key_base: 4a12d537f9f432a2681433e8d5cc48419415ab251d1bcae0ae87de62d4ae6129616891ecb8b45b336188f1fdbaf3375a30dd9b2b7324924b63cae871e955b47f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
